django_gems/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = (
    path('admin/', admin.site.urls),
    path('', include('django_gems.common.urls')),
    path('', include('django_gems.jewelry.urls')),
    path('', include('django_gems.user_account.urls')),
    path('', include('django_gems.shopping_cart.urls')),
    path('', include('django_gems.order.urls')),
    path('', include('django_gems.user_profile.urls')),
    path('', include('django_gems.wishlist.urls')),
)

django_gems/wishlist/urls.py
from django.urls import path

from django_gems.wishlist.views import (
    LikeJewelryView,
    DisplayedLikedJewelries
)

urlpatterns = (
    path(
        'like/<int:jewelry_pk>',
        LikeJewelryView.as_view(),
        name='like_jewelry'
    ),
    path(
        'likes/',
        DisplayedLikedJewelries.as_view(),
        name='display_liked_jewelries'
    ),
)

django_gems/inventory/models.py
from django.db import models
from django_gems.common.utils import ChoicesMaxLengthMixin
from django.utils.translation import gettext_lazy as _
from django_gems.jewelry.models import Jewelry


class Inventory(models.Model):
    class Meta:
        verbose_name_plural = 'Inventories'
    class PriceChoices(ChoicesMaxLengthMixin, models.TextChoices):
        V_750 = '10_000, 25_000', _('10,000.00 - 25,000.00')
        V_1500 = '25_000, 50_000', _('25,000.00 - 50,000.00')
        V_3000 = '50_000, 75_000', _('50,000.00 - 75,000.00')
        V_5000 = '75_000, 100_000', _('75,000.00 - 100,000.00')
        V_100000 = '100_000, 1_000_000', _('ABOVE 100,000.00')

    quantity = models.PositiveIntegerField()

    jewelry = models.ForeignKey(
        to=Jewelry,
        on_delete=models.CASCADE,
    )

    price = models.DecimalField(
        max_length=PriceChoices.max_length(),
        max_digits=10,
        decimal_places=2,
    )

    discounted_price = models.DecimalField(
        max_digits=10,
        decimal_places=2,
        null=True,
        blank=True,
    )

    created_at = models.DateTimeField(
        auto_now_add=True,
        editable=False,
    )

    updated_at = models.DateTimeField(
        auto_now=True,
        editable=False,
    )

    def __str__(self):
        return f'Inventory ID: {self.pk}'

django_gems/wishlist/models.py
from django.contrib.auth import get_user_model
from django.db import models
from django_gems.jewelry.models import Jewelry

UserModel = get_user_model()


class JewelryLike(models.Model):
    class Meta:
        unique_together = ('jewelry', 'user')

    jewelry = models.ForeignKey(
        Jewelry,
        on_delete=models.CASCADE,
        null=False,
        blank=True,
    )

    user = models.ForeignKey(
        to=UserModel,
        on_delete=models.CASCADE,
    )

django_gems/wishlist/views.py
from django.shortcuts import redirect
from django.views.generic import ListView
from django.views import View
from django_gems.common.mixins import NavigationBarMixin
from django_gems.jewelry.models import Jewelry
from django_gems.wishlist.models import JewelryLike


class LikeJewelryView(View):
    def get(self, request, *args, **kwargs):
        jewelry_pk = kwargs.get('jewelry_pk')

        if request.user.is_authenticated:
            user_id = request.user.pk

            kwargs = {
                'jewelry_id': jewelry_pk,
                'user_id': user_id,
            }

            user_liked_jewelry = JewelryLike.objects.filter(**kwargs).first()

            if user_liked_jewelry:
                user_liked_jewelry.delete()
            else:
                JewelryLike.objects.create(**kwargs)

        else:

            liked_jewelries = request.session.get('liked_jewelries', [])

            if jewelry_pk in liked_jewelries:
                liked_jewelries.remove(jewelry_pk)
            else:
                liked_jewelries.append(jewelry_pk)

            request.session['liked_jewelries'] = liked_jewelries

        return redirect(request.META.get('HTTP_REFERER', '/'))


class DisplayedLikedJewelries(NavigationBarMixin, ListView):
    model = Jewelry
    template_name = 'wishlist/liked_jewelries.html'
    context_object_name = 'jewelries'
    paginate_by = 6

    def get_queryset(self):
        queryset = super().get_queryset()

        if self.request.user.is_authenticated:

            likes_pks = JewelryLike.objects. \
                filter(user_id=self.request.user.pk). \
                values_list('jewelry_id', flat=True)

            queryset = queryset.filter(id__in=likes_pks)

            for jewelry in queryset:
                jewelry.liked_by_user = jewelry.jewelrylike_set. \
                    filter(user=self.request.user). \
                    exists()
        else:
            liked_jewelries = self.request.session.get('liked_jewelries', [])
            likes_pks = liked_jewelries

            queryset = queryset.filter(id__in=likes_pks)

            for jewelry in queryset:
                jewelry.liked_by_user = jewelry.pk in liked_jewelries

        return queryset

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)

        count_liked_jewelries = len(self.get_queryset())

        context['count_liked_jewelries'] = count_liked_jewelries

        nav_bar_context = self.get_nav_bar_context()
        context.update(nav_bar_context)

        return context

templates/wishlist/jewelry-card.html
<section class="cards">
    {% for jewelry in object_list %}
        <article class="card">
            <div class="thumbnail">
                <a
                        href="{% url 'view_jewelry' jewelry.pk %}?page={{ page_obj.number }}"
                        title="{{ jewelry.title }}">
                    <img
                            class="thumbnail__img"
                            src="{{ jewelry.first_image_url }}"
                            alt="{{ jewelry.title }} image"
                    />
                </a>
                {% include 'wishlist/like-button.html' %}
{#                <a href="{% url 'like_jewelry' jewelry_pk=jewelry.pk %}" class="like-button">#}
{#                    {% if jewelry.liked_by_user %}#}
{#                        <svg style="color: #FFA7A6"#}
{#                             xmlns="http://www.w3.org/2000/svg"#}
{#                             width="24"#}
{#                             height="24"#}
{#                             fill="currentColor"#}
{#                             class="bi bi-heart-fill"#}
{#                             viewBox="0 0 16 16">#}
{#                            <path fill-rule="evenodd"#}
{#                                  d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"#}
{#                                  fill="#FFA7A6">#}
{#                            </path>#}
{#                        </svg>#}
{#                    {% else %}#}
{#                        <svg aria-label="Like"#}
{#                             color="#262626"#}
{#                             fill="#FFA7A6"#}
{#                             height="24"#}
{#                             role="img"#}
{#                             viewBox="0 0 48 48"#}
{#                             width="24">#}
{#                            <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4#}
{#                        11.5 0 6.8-5.9 11-11.5 16S25 41.3 24#}
{#                        41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3#}
{#                        11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3#}
{#                        1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9#}
{#                        1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9#}
{#                        1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1#}
{#                        0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3#}
{#                        1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3#}
{#                        1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2#}
{#                        7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6#}
{#                        48 25 48 17.6c0-8-6-14.5-13.4-14.5z">#}
{#                            </path>#}
{#                        </svg>#}
{#                    {% endif %}#}
{#                </a>#}
            </div>
            <div class="content">
                <h2 class="content__title">
                    {{ jewelry.title }}
                </h2>
                <p class="content__category">
                    {{ jewelry.category.get_title_display }}
                </p>
                <ul class="content__characteristics" role="list">
                    {% for metal_info in jewelry.jewelry_metals.all %}
                        <li class="characteristic">
                            <i class="metal__icon fa-solid fa-coins"></i>
                            {% if metal_info.gold_carat %}
                                <span>{{ metal_info.gold_carat.get_weight_display }} {{ metal_info.metal.get_title_display }}</span>
                            {% else %}
                                <span>{{ metal_info.metal.get_title_display }}</span>
                            {% endif %}
                        </li>
                    {% endfor %}
                    {% for stone_info in jewelry.jewelry_stones.all %}
                        <li class="characteristic">
                            <i class="stone__icon fa-solid fa-gem"></i>
                            {% if stone_info.stone_carat %}
                                <span>{{ stone_info.stone_color.get_title_display }} {{ stone_info.stone_type.get_title_display }} {{ stone_info.stone_carat }}ct.</span>
                            {% else %}
                                <span>{{ stone_info.stone_color.get_title_display }} {{ stone_info.stone_type.get_title_display }}</span>
                            {% endif %}
                        </li>
                    {% endfor %}
                </ul>
                {% with inventory=jewelry.inventory_set.first %}
                    <p class="content__price">
                        <i class="price__icon fa-solid fa-sack-dollar"></i> {{ inventory.price|floatformat:0 }}
                    </p>
                {% endwith %}
            </div>
        </article>
    {% endfor %}
</section>

templates/wishlist/like-button.html
<a href="{% url 'like_jewelry' jewelry_pk=jewelry.pk %}" class="like-button">
    {% if jewelry.liked_by_user %}
        <svg style="color: #ffb7ce"
             xmlns="http://www.w3.org/2000/svg"
             width="24"
             height="24"
             fill="currentColor"
             class="bi bi-heart-fill"
             viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                  d="M8 1.314C12.438-3.248 23.534 4.735 8 15-7.534 4.736 3.562-3.248 8 1.314z"
                  fill="#ffb7ce">
            </path>
        </svg>
    {% else %}
        <svg aria-label="Like"
             color="#262626"
             fill="#ffb7ce"
             height="24"
             role="img"
             viewBox="0 0 48 48"
             width="24">
            <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                        11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                        41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                        11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                        1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                        1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                        1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                        0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                        1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                        1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                        7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                        48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
            </path>
        </svg>
    {% endif %}
</a>

templates/wishlist/liked_jewelries.html
{% extends 'base/base.html' %}
{#{% load cache %}#}
{% block page_content %}
{#    {% cache 10 background_image %}#}
    <article class="wish-list-card">
        <img class="img-bg"
             src="https://res.cloudinary.com/deztgvefu/image/upload/v1706346310/template_images/largeherod_l3_candy23_a_red_xczfkn.webp"
             alt="image">
        <div class="wish-list-content-top">
            <h2 class="wish-list-tag">
                {% if count_liked_jewelries %}
                    Your Wish List ({{ count_liked_jewelries }})
                {% else %}
                    Your Wish List (0)
                {% endif %}
            </h2>
            <p class="wish-list-title">
                Your favorite item(s) are below.
                <br>Wishes can come true, especially when you dream.
            </p>
        </div>
        <div class="wish-list-content-bottom">
            <div class="meta-info">
                <div class="designer">
                    <img src="https://res.cloudinary.com/deztgvefu/image/upload/v1706426486/template_images/cute-little-pink-cat-watercolor-png_2_kxmwtq.webp">
                </div>
                <p class="name">Beatris Ilieve</p>
                <p class="email">beatrisilieve@icloud.com</p>
            </div>
        </div>
    </article>
{#    {% endcache %}#}
    {% if count_liked_jewelries %}
        {% include 'wishlist/jewelry-card.html' %}
        {% include 'common/pagination.html' %}
    {% endif %}
{% endblock %}